name: Test Build

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build_windows:
    name: Build wheels on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        env:
          CIBW_BUILD: "*win_amd64"
          CIBW_BUILD_FRONTEND: build
        uses: pypa/cibuildwheel@v2.22

  build_macos:
    name: Build wheels on MacOS
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Xcode Switch
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Build
        env:
          CIBW_BUILD: "*mac*"
          CIBW_BUILD_FRONTEND: build
          MACOSX_DEPLOYMENT_TARGET: "13.3"
        uses: pypa/cibuildwheel@v2.22

  build_linux:
    name: Build wheels on Linux
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Build
        run: |
          pipx run build
          platform="$(ldd --version | awk '/ldd/{gsub(/\./, "_", $NF); print "manylinux_" $NF "_x86_64"}')"
          pipx run wheel tags --remove --platform=${platform} dist/*linux_x86_64.whl

  build_sdist:
    name: Build sdist
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: pipx run build --sdist
